export const APPOINTMENT_STATUSES = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  CONCLUDED: 'CONCLUDED',
  CANCELLED: 'CANCELLED',
}

export const APPOINTMENT_STATUS_LABELS = {
  [APPOINTMENT_STATUSES.PENDING]: 'Agendado',
  [APPOINTMENT_STATUSES.CONFIRMED]: 'Confirmado',
  [APPOINTMENT_STATUSES.CONCLUDED]: 'Concluído',
  [APPOINTMENT_STATUSES.CANCELLED]: 'Cancelado',
}
