import {
  Spa,
  Film,
  Dumbbell,
  PawPrint,
  Apple,
  Users,
  Sun,
  Store,
  TreePine,
  Sofa,
  Salad,
  ShoppingBasket,
  Tennis,
  Utensils,
  Hammer,
  Bed,
  Network,
  WandSparkles,
  Flower2,
  PartyPopper,
  WashingMachine,
  Building,
  Gamepad2,
} from "lucide-react";

export const EFeatureIcon = {
  SPA: Spa,
  CINEMA: Film,
  HALTER: Dumbbell,
  PET: PawPrint,
  POMAR: Apple,
  USUARIOS: Users,
  SOLARIO: Sun,
  LOJA: Store,
  PRACA: TreePine,
  LOUNGE: Sofa,
  PIQUENIQUE: Salad,
  CESTA_MERCADO: ShoppingBasket,
  BEACH_TENIS: Tennis,
  FORNO_PIZZA: Utensils,
  OFICINA: Hammer,
  REDE: Bed,
  COWORKING: Network,
  MAQUIAGEM: WandSparkles,
  BRINQUEDO: Flower2,
  SALAO_FESTAS: PartyPopper,
  LAVANDERIA: WashingMachine, // Corrigido!
  ROOFTOP: Building,
  CONTROLE_VIDEOGAME: Gamepad2,
};
